version: "3.9"
services:
  webapp:
    container_name: nihongo-stats-webapp
    image: 'node:16-alpine'
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: "sh -c 'npm install && npm run dev'"
    ports:
      - "3000:3000"

