export type BunProUser = {
    id: string,
    email: string,
    username: string,
    createdAt: Date,
    updatedAt: Date,
    hideEnglish: string,
    furigana: string,
    lightMode: string,
    batchSize: number,
    studyLevel: string,
    vacationMode: boolean,
    language: string | null,
    bunnyMode: string,
    reviewEnglish: string,
    wanikaniApiKey: string,
    knownKanji: { [key: string]: string },
    fontSizing: string,
    newNotifications: boolean,
    level: number,
    xp: number,
    prevLevelXp: number,
    nextLevelXp: number,
    studyStreak: number,
    name: string | null,
    receiveLanguageLearningNewsletter: string,
    receiveProgressEmails: string,
    receiveInactivityEmails: string,
    optInToBeta: string,
    forecastDataView: string,
    mobileNavLocation: string,
    enableColorBlindAssistance: string,
    allowFeedbackReplyEmails: boolean,
    casualFormalFocus: string,
    splitReviews: string,
    listeningMode: string,
    autoPlayReviewAudio: string,
    ghostReviewSettings: string,
    primaryTextbook: string,
    unsubscribeFromEmail: string,
    timeZone: string
}

