name: Build and Deploy to Google Cloud

on:
  release:
    types: [published]

env:
  REGISTRY: us-central1-docker.pkg.dev
  IMAGE_NAME: nihongo-stats/containers/nihongo-stats-nginx

jobs:

  Build-React-App:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: echo $GITHUB_REF_NAME > assets/version.txt
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: dist

  Build-Docker-Image:
    needs: [Build-React-App]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: react-app
          path: dist

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: nihongo-stats

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}

      - run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@965c6a410d446a30e95d35052c67d6eded60dad6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

  Deploy-To-Cloud-Run:
    needs: [Build-Docker-Image]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: nihongo-stats

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Cloud Run
        run: gcloud run deploy nihongo-stats --region us-central1 --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_REF_NAME