name: Retag image and Deploy to Google Cloud

on:
  release:
    types: [published]

env:
  REGISTRY: us-central1-docker.pkg.dev
  IMAGE_NAME: nihongo-stats/containers/nihongo-stats-nginx

jobs:

  Retag-Image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: nihongo-stats

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.1
        with:
          credentials_json: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}

      - run: gcloud auth configure-docker ${{ env.REGISTRY }}
      
      - name: Tag image
        run: gcloud artifacts docker tags add ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_REF_NAME


  Deploy-To-Cloud-Run:
    needs: [Retag-Image]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: nihongo-stats

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.1
        with:
          credentials_json: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Cloud Run
        run: gcloud run deploy nihongo-stats --region us-central1 --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_REF_NAME